external_templates:
  - file: /config/templates/collections
  - file: /config/templates/dynamic_collections

collections:
  "Trending Now":
    template: { name: Chart,
                level: "+++" }
    url_poster: https://i.imgur.com/6jZNd6W.png
    trakt_chart:
      chart: trending
      limit: 30
    collection_order: custom
    sync_mode: sync
    visible_library: true
    visible_home: true
    visible_shared: true
