services:
  owntracks-recorder:
    container_name: owntracks-recorder
    image: owntracks/recorder
    restart: unless-stopped
    ports:
      - 8083:8083
    environment:
      - OTR_PORT=0
      - OTR_PASS=$RECORDER_PASSWORD
    volumes:
      - ${CONFIG_LOCATION}/recorder/store:/store

  owntracks-frontend:
    container_name: owntracks-frontend
    image: owntracks/frontend
    restart: unless-stopped
    networks:
      - default
      - local-services
    environment:
      SERVER_HOST: owntracks-recorder
      SERVER_PORT: 8083

networks:
  default: # default network for every container
    name: owntracks-network-default # since the key has to be default this is the actual name
    driver: bridge
  local-services:
    external: true
