services:
  # real debrid webdav
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:v0.9.3-hotfix.11
    container_name: zurg-streaming
    restart: unless-stopped
    healthcheck:
      test: curl -f localhost:9999/dav/version.txt || exit 1
    ports:
      - :9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/zurg/config.yml:/app/config.yml
      - zurgdata:/app/data
  
  # mount zurg webdav
  rclone:
    image: rclone/rclone:latest
    container_name: rclone-streaming
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/zurg/rclone.conf:/config/rclone/rclone.conf
      - /mnt/remote/realdebrid:/data:rshared
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    command: 'mount zurg: /data --allow-non-empty --allow-other --uid=1000 --gid=1000 --dir-cache-time 10s'

  # media server
  plex:
    container_name: plex-streaming
    image: ghcr.io/hotio/plex
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - UMASK=002
    ports:
      - 32401:32400 # have to expose plex for it to work (i think)
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/dri:/dev/dri
      - ${CONFIG_LOCATION}/plex:/config
      - ${MEDIA_LOCATION}:/server/data
      - ${TRANSCODES_LOCATION}/plex-streaming:/transcode
      - /mnt/remote/realdebrid:/mnt/remote/realdebrid
    depends_on:
      - rclone

  # downloader - adds torrent files to real-debrid
  blackhole:
    build:
      context: https://github.com/westsurname/scripts.git
      dockerfile: Dockerfile.blackhole
    container_name: blackhole-streaming
    user: 1000:1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_LOCATION}:/server/data
      - /mnt/remote/realdebrid:/mnt/remote/realdebrid
    env_file:
      - ${CONFIG_LOCATION}/blackhole/west.env
    depends_on:
      - rclone
    networks:
      - local-services
    restart: unless-stopped

  # media download managers
  radarr:
    image: ghcr.io/hotio/radarr:release
    container_name: radarr-streaming
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - :7878
    networks:
      - local-services
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/radarr:/config
      - ${MEDIA_LOCATION}:/server/data
      - /mnt/remote/realdebrid:/mnt/remote/realdebrid
    depends_on:
      - rclone
      - blackhole

  sonarr:
    image: ghcr.io/hotio/sonarr:release
    container_name: sonarr-streaming
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - :8989
    networks:
      - local-services
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/sonarr:/config
      - ${MEDIA_LOCATION}:/server/data
      - /mnt/remote/realdebrid:/mnt/remote/realdebrid
    depends_on:
      - rclone
      - blackhole
  
  # indexer manager
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release
    container_name: prowlarr-streaming
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - :9696
    networks:
      - local-services
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/prowlarr:/config
      - ${MEDIA_LOCATION}:/server/data
      - ${CUSTOM_LOCATION}/Prowlarr-Indexers/Custom:/config/Definitions/Custom
      - /mnt/remote/realdebrid:/mnt/remote/realdebrid
    depends_on:
      - rclone
      - flaresolverr

  # download manager configurator
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr-streaming
    env_file:
      - recyclarr.env
    environment:
      - CRON_SCHEDULE=@daily
      - RECYCLARR_CREATE_CONFIG=true
    user: 1000:1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/recyclarr:/config

  # subtitle downloader
  bazarr:
    image: ghcr.io/hotio/bazarr
    container_name: bazarr-streaming
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/bazarr:/config
      - ${MEDIA_LOCATION}:/server/data
      - /mnt/remote/realdebrid:/mnt/remote/realdebrid
    ports:
      - :6767
    networks:
      - local-services
    restart: unless-stopped
    depends_on:
      - rclone

  # misc
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr-streaming
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - :8191
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  # todo
  # plex-meta-manager:
  #   image: meisnate12/plex-meta-manager
  #   container_name: plex-meta-manager-streaming
  #   environment:
  #     # - PMM_RUN=true
  #   restart: unless-stopped
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ${CONFIG_LOCATION}/plex-meta-manager:/config
  #     - ${MEDIA_LOCATION}:/server/data
  #     - /mnt/remote/realdebrid:/mnt/remote/realdebrid
  #   depends_on:
  #     - rclone
  #     - plex

volumes:
  zurgdata:

networks:
  default: # default network for every container
    name: streaming # since the key has to be default this is the actual name
    driver: bridge
  local-services:
    external: true