services:
  caddy-internal:
    image: ghcr.io/f0e/caddy-custom
    container_name: caddy-internal
    env_file:
      - caddy.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_LOCATION}/caddy/data:/data
      - ${HOMEPAGE_LOCATION}:/homepage
      - ${CONFIG_LOCATION}/caddy/config:/config
      - ${CADDYFILE_LOCATION}:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    networks:
      - local-services # todo: i don't like that every other service has to run on the br0 network, but i can't figure out how to connect to them otherwise. if i create a separate br0 network just for caddy then if i include the other bridge network here it'll try to map ports still
    restart: unless-stopped

  authelia-redis:
    container_name: authelia-redis
    image: docker.io/library/redis:alpine
    command: >
      --requirepass ${REDIS_PASS}
    volumes:
      - ${CONFIG_LOCATION}/redis:/data
    networks:
      - local-services
    restart: unless-stopped

  authelia-postgres:
    container_name: authelia-postgres
    image: docker.io/library/postgres:16-alpine
    volumes:
      - ${CONFIG_LOCATION}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    networks:
      - local-services
    restart: unless-stopped

  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    networks:
      - local-services
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_LOCATION}/authelia:/config
    expose:
      - 9091
    restart: unless-stopped
    depends_on:
      - authelia-redis
      - authelia-postgres

networks:
  local-services:
    external: true
