external_templates:
  - file: /config/templates/collections
  - file: /config/templates/dynamic_collections

collections:
  ### New Content
  "Now On Plex":
    template: { name: New,
                level: "++++" }
    smart_filter:
      type: show
      sort_by: release.desc
      all:
        # Shows added in the last 30 days
        added: 30
    sync_mode: sync
    visible_library: true
    visible_home: true
    visible_shared: true

  "New Episodes":
    template: { name: New,
                level: "+++" }
    smart_filter:
      type: episode
      sort_by: release.desc
      all:
        # Episode added in the last 7 days
        release: 7
    sync_mode: sync
    visible_home: true
    visible_shared: true
    visible_library: true
